/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canciones;

import java.awt.Component;
import java.awt.Cursor;
import java.io.File;
import java.net.URL;
import javax.media.Manager;
import javax.media.Player;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JFrame;
/**
 *
 * @author Alberto Villarreal
 */
public class CancionAraña extends javax.swing.JFrame {
        URL urlArchivoMusica;
        Player reproductor;


        //Recalcar el tamaño de la interfaz
	private final int WINDOW_WIDTH = 909;
	private final int WINDOW_HEIGHT = 655;
        public Clip clip;
        int vez = 0;
        LetraAraña Letra = new LetraAraña();

    /**
     * Creates new form FabricaDePalabras
     */
    public CancionAraña() {
                initComponents();
                //botonesTransparentes(); //manda a llamar al metodo botonesTransparentes
                botonesTransparentes();
                //this.setLocationRelativeTo(null); //Para que apareza la interfaz en el centro
		// Set window size.
		setSize(WINDOW_WIDTH, WINDOW_HEIGHT);
                setTitle("LEON"); //Titulo del programa
		setResizable(false); //Remueve el boton de maximizar pantalla
		// Specify what happens when close button is clicked.
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ConfiguracionButton = new javax.swing.JButton();
        RegresarButton = new javax.swing.JButton();
        PlayButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        InstruccionLabel = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        LetraButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(201, 217, 230));
        jPanel1.setLayout(null);

        ConfiguracionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuracion_6.png"))); // NOI18N
        ConfiguracionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfiguracionButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ConfiguracionButton);
        ConfiguracionButton.setBounds(0, 560, 60, 70);

        RegresarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar_2.png"))); // NOI18N
        RegresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RegresarButton);
        RegresarButton.setBounds(830, 560, 80, 70);

        PlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/play-bdutton2.png"))); // NOI18N
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PlayButton);
        PlayButton.setBounds(420, 20, 70, 70);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Canción de Dominio Público");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(480, 70, 290, 30);

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Compositor original: Desconocido ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 10, 460, 30);

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Interprete:  La Granja de Zenón");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 40, 450, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(60, 529, 780, 110);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wincy128.png"))); // NOI18N
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(390, 210, 128, 128);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blank.png"))); // NOI18N
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(585, 370, 30, 40);

        InstruccionLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        InstruccionLabel.setText("Incy Wincy Araña");
        jPanel1.add(InstruccionLabel);
        InstruccionLabel.setBounds(320, 100, 270, 40);
        if(vez==0){
            try{
                stopSound();
                urlArchivoMusica = new URL("file:"+"src/sonidos/Incy_wincy_araña.wav");//url del archivo a reproducir
                reproductor = Manager.createRealizedPlayer(urlArchivoMusica);
                Component controles = reproductor.getControlPanelComponent();
                if(controles != null){
                    this.add(controles);
                    controles.setLocation(305,380);
                    controles.setSize(300, 25);
                    jPanel1.add(controles);
                }
                reproductor.start();
            }catch(Exception e){
                System.out.println("se encontró un error al intentar reproducir el archivo");
            }
            vez = 1;
        }else{
            reproductor.stop();
            vez=0;
        }

        NextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/next_arrow.png"))); // NOI18N
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });
        jPanel1.add(NextButton);
        NextButton.setBounds(590, 230, 160, 110);

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back_arrow - copia.png"))); // NOI18N
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton);
        BackButton.setBounds(140, 230, 160, 110);

        LetraButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/music_note.png"))); // NOI18N
        LetraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LetraButton);
        LetraButton.setBounds(430, 440, 50, 64);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarButtonActionPerformed
        //boton para volver al menu principal, se declara tamaño y al centro
        MenuCanciones Menu = new MenuCanciones();
        Menu.setSize(909, 655);
        Menu.setLocationRelativeTo(null);
        Menu.setVisible(true);
        Letra.dispose();
        reproductor.stop();//detener la cancion al salir de la interfaz
        stopSound();
        this.dispose();

    }//GEN-LAST:event_RegresarButtonActionPerformed

    private void ConfiguracionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfiguracionButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ConfiguracionButtonActionPerformed

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        reproductor.stop();
        stopSound();
        playSound("Incy_Wincy_ArañaVoz");
    }//GEN-LAST:event_PlayButtonActionPerformed

    private void LetraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraButtonActionPerformed
        Letra.setSize(217, 300);
        Letra.setLocationRelativeTo(null);
        Letra.setVisible(true);
        stopSound();
    }//GEN-LAST:event_LetraButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        //boton para volver al menu principal, se declara tamaño y al centro
        CancionEstrellita Cancion = new CancionEstrellita();
        Cancion.setSize(909, 655);
        Cancion.setLocationRelativeTo(null);
        Cancion.setVisible(true);
        Letra.dispose();
        reproductor.stop();//detener la cancion al salir de la interfaz
        stopSound();
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        //boton para volver al menu principal, se declara tamaño y al centro
        CancionMaria Cancion = new CancionMaria();
        Cancion.setSize(909, 655);
        Cancion.setLocationRelativeTo(null);
        Cancion.setVisible(true);
        Letra.dispose();
        reproductor.stop();//detener la cancion al salir de la interfaz
        stopSound();
        this.dispose();
    }//GEN-LAST:event_NextButtonActionPerformed

     public void botonesTransparentes(){
        ConfiguracionButton.setOpaque(false);
        ConfiguracionButton.setContentAreaFilled(false);
        ConfiguracionButton.setBorderPainted(false);
        ConfiguracionButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ConfiguracionButton.setFocusPainted(false);
        RegresarButton.setOpaque(false);
        RegresarButton.setContentAreaFilled(false);
        RegresarButton.setBorderPainted(false);
        RegresarButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        RegresarButton.setFocusPainted(false);
        PlayButton.setOpaque(false);
        PlayButton.setContentAreaFilled(false);
        PlayButton.setBorderPainted(false);
        PlayButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        PlayButton.setFocusPainted(false);
        NextButton.setOpaque(false);
        NextButton.setContentAreaFilled(false);
        NextButton.setBorderPainted(false);
        NextButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        NextButton.setFocusPainted(false);
        BackButton.setOpaque(false);
        BackButton.setContentAreaFilled(false);
        BackButton.setBorderPainted(false);
        BackButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        BackButton.setFocusPainted(false);
        LetraButton.setOpaque(false);
        LetraButton.setContentAreaFilled(false);
        LetraButton.setBorderPainted(false);
        LetraButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        LetraButton.setFocusPainted(false);
        
 }
     
     private void playSound(String File) { // Play a wav file specified by fileName
        try {
            String path = "src/sonidos/" + File + ".wav";
            File file = new File(path);
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(file);
            clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (Exception e) {
        }
    }
    
    //metodo para detener el sonido
    private void stopSound() { // Play a wav file specified by fileName
        try {
            clip.stop();
        } catch (Exception e) {
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancionAraña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancionAraña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancionAraña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancionAraña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancionAraña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton ConfiguracionButton;
    private javax.swing.JLabel InstruccionLabel;
    private javax.swing.JButton LetraButton;
    private javax.swing.JButton NextButton;
    private javax.swing.JButton PlayButton;
    private javax.swing.JButton RegresarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
