/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canciones;

import interfaces.*;
import complementos.TrasladadorPalabras;
import java.awt.Component;
import letras.LetraA;
import java.awt.Cursor;
import java.io.File;
import java.net.URL;
import javax.media.Manager;
import javax.media.Player;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JFrame;
import repasar.RepasarMenu;
import silabas.SilabaTaza;
/**
 *
 * @author Alberto Villarreal
 */
public class MenuCanciones extends javax.swing.JFrame {
        //Recalcar el tamaño de la interfaz
	private final int WINDOW_WIDTH = 909;
	private final int WINDOW_HEIGHT = 655;
        URL urlArchivoMusica;
        Player reproductor;
        public Clip clip;
        public int vez = 0;
    /**
     * Creates new form FabricaDePalabras
     */
    public MenuCanciones() {
        initComponents();
                //botonesTransparentes(); //manda a llamar al metodo botonesTransparentes
                botonesTransparentes();
                //this.setLocationRelativeTo(null); //Para que apareza la interfaz en el centro
		// Set window size.
		setSize(WINDOW_WIDTH, WINDOW_HEIGHT);
                setTitle("LEON"); //Titulo del programa
		setResizable(false); //Remueve el boton de maximizar pantalla
		// Specify what happens when close button is clicked.
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		// Generate an instance of the class that accesses
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ConfiguracionButton = new javax.swing.JButton();
        RegresarButton = new javax.swing.JButton();
        PlayAllButton = new javax.swing.JButton();
        LetrasDeArribaLabel = new javax.swing.JLabel();
        LetrasDeAbajoLabel = new javax.swing.JLabel();
        Cancion1Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Cancion2Button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Cancion3Button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Cancion4Button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Cancion5Button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Cancion6Button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Cancion7Button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Cancion8Button = new javax.swing.JButton();
        EscucharTodosLabel = new javax.swing.JLabel();
        PlayButton = new javax.swing.JButton();
        Imagen8Button = new javax.swing.JButton();
        Imagen1Button = new javax.swing.JButton();
        Imagen2Button = new javax.swing.JButton();
        Imagen3Button = new javax.swing.JButton();
        Imagen4Button = new javax.swing.JButton();
        Imagen5Button = new javax.swing.JButton();
        Imagen6Button = new javax.swing.JButton();
        Imagen7Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(201, 217, 230));
        jPanel1.setLayout(null);

        ConfiguracionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuracion_6.png"))); // NOI18N
        ConfiguracionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfiguracionButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ConfiguracionButton);
        ConfiguracionButton.setBounds(0, 490, 60, 70);

        RegresarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar_2.png"))); // NOI18N
        RegresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RegresarButton);
        RegresarButton.setBounds(830, 490, 80, 70);

        PlayAllButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/playAll.png"))); // NOI18N
        PlayAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayAllButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PlayAllButton);
        PlayAllButton.setBounds(520, 500, 32, 32);

        LetrasDeArribaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/15primeras_letras.png"))); // NOI18N
        jPanel1.add(LetrasDeArribaLabel);
        LetrasDeArribaLabel.setBounds(0, 0, 910, 71);

        LetrasDeAbajoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/15ultimas_letras.png"))); // NOI18N
        jPanel1.add(LetrasDeAbajoLabel);
        LetrasDeAbajoLabel.setBounds(0, 550, 910, 80);

        Cancion1Button.setFont(new java.awt.Font("Smart Kid", 0, 24)); // NOI18N
        Cancion1Button.setForeground(new java.awt.Color(51, 51, 255));
        Cancion1Button.setText("<html><u>Estrellita Dónde Estás</u></html>");
        Cancion1Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Cancion1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancion1ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Cancion1Button);
        Cancion1Button.setBounds(160, 180, 240, 23);

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 22)); // NOI18N
        jLabel1.setText("1.- ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 170, 40, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 22)); // NOI18N
        jLabel2.setText("2.- ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 240, 40, 40);

        Cancion2Button.setFont(new java.awt.Font("Smart Kid", 0, 24)); // NOI18N
        Cancion2Button.setForeground(new java.awt.Color(51, 51, 255));
        Cancion2Button.setText("<html><u>Incy Wincy Araña</u></html>");
        Cancion2Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Cancion2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancion2ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Cancion2Button);
        Cancion2Button.setBounds(160, 250, 200, 23);

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 22)); // NOI18N
        jLabel3.setText("3.- ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 310, 40, 40);

        Cancion3Button.setFont(new java.awt.Font("Smart Kid", 0, 24)); // NOI18N
        Cancion3Button.setForeground(new java.awt.Color(51, 51, 255));
        Cancion3Button.setText("<html><u>María Tiene Un Corderito</u></html>");
        Cancion3Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Cancion3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancion3ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Cancion3Button);
        Cancion3Button.setBounds(160, 320, 280, 23);

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 22)); // NOI18N
        jLabel4.setText("4.- ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 380, 40, 40);

        Cancion4Button.setFont(new java.awt.Font("Smart Kid", 0, 24)); // NOI18N
        Cancion4Button.setForeground(new java.awt.Color(51, 51, 255));
        Cancion4Button.setText("<html><u>El Granjero en la Cañada</u></html>");
        Cancion4Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Cancion4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancion4ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Cancion4Button);
        Cancion4Button.setBounds(160, 390, 270, 23);

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 22)); // NOI18N
        jLabel5.setText("5.- ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(570, 170, 40, 40);

        Cancion5Button.setFont(new java.awt.Font("Smart Kid", 0, 24)); // NOI18N
        Cancion5Button.setForeground(new java.awt.Color(51, 51, 255));
        Cancion5Button.setText("<html><u>La Canción del ABC</u></html>");
        Cancion5Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Cancion5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancion5ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Cancion5Button);
        Cancion5Button.setBounds(600, 180, 220, 23);

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 0, 22)); // NOI18N
        jLabel6.setText("6.- ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(570, 240, 40, 40);

        Cancion6Button.setFont(new java.awt.Font("Smart Kid", 0, 24)); // NOI18N
        Cancion6Button.setForeground(new java.awt.Color(51, 51, 255));
        Cancion6Button.setText("<html><u>El Viejo McDonald</u></html>");
        Cancion6Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Cancion6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancion6ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Cancion6Button);
        Cancion6Button.setBounds(600, 250, 210, 23);

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 0, 22)); // NOI18N
        jLabel7.setText("7.- ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(570, 310, 40, 40);

        Cancion7Button.setFont(new java.awt.Font("Smart Kid", 0, 24)); // NOI18N
        Cancion7Button.setForeground(new java.awt.Color(51, 51, 255));
        Cancion7Button.setText("<html><u>Un Yankee Viaja a la Ciudad</u></html>");
        Cancion7Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Cancion7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancion7ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Cancion7Button);
        Cancion7Button.setBounds(600, 320, 290, 23);

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 0, 22)); // NOI18N
        jLabel8.setText("8.- ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(570, 380, 40, 40);

        Cancion8Button.setFont(new java.awt.Font("Smart Kid", 0, 24)); // NOI18N
        Cancion8Button.setForeground(new java.awt.Color(51, 51, 255));
        Cancion8Button.setText("<html><u>Rema Tu Bote</u></html>");
        Cancion8Button.setToolTipText("");
        Cancion8Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Cancion8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancion8ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Cancion8Button);
        Cancion8Button.setBounds(600, 390, 170, 23);

        EscucharTodosLabel.setFont(new java.awt.Font("Smart Kid", 0, 24)); // NOI18N
        EscucharTodosLabel.setText("Escuchar todas: ");
        jPanel1.add(EscucharTodosLabel);
        EscucharTodosLabel.setBounds(370, 500, 160, 30);

        PlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/play-bdutton2.png"))); // NOI18N
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PlayButton);
        PlayButton.setBounds(420, 80, 70, 70);

        Imagen8Button.setBackground(new java.awt.Color(240, 255, 153));
        Imagen8Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bote64.png"))); // NOI18N
        Imagen8Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Imagen8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imagen8ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Imagen8Button);
        Imagen8Button.setBounds(500, 370, 64, 64);

        Imagen1Button.setBackground(new java.awt.Color(204, 255, 153));
        Imagen1Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estrellita64.png"))); // NOI18N
        Imagen1Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Imagen1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imagen1ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Imagen1Button);
        Imagen1Button.setBounds(60, 160, 64, 64);

        Imagen2Button.setBackground(new java.awt.Color(240, 255, 153));
        Imagen2Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wincy64.png"))); // NOI18N
        Imagen2Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Imagen2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imagen2ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Imagen2Button);
        Imagen2Button.setBounds(60, 230, 64, 64);

        Imagen3Button.setBackground(new java.awt.Color(240, 255, 153));
        Imagen3Button.setForeground(new java.awt.Color(204, 204, 204));
        Imagen3Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corderito64.png"))); // NOI18N
        Imagen3Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Imagen3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imagen3ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Imagen3Button);
        Imagen3Button.setBounds(60, 300, 64, 64);

        Imagen4Button.setBackground(new java.awt.Color(240, 255, 153));
        Imagen4Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/granjero64.png"))); // NOI18N
        Imagen4Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Imagen4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imagen4ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Imagen4Button);
        Imagen4Button.setBounds(60, 370, 64, 64);

        Imagen5Button.setBackground(new java.awt.Color(240, 255, 153));
        Imagen5Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abc64.png"))); // NOI18N
        Imagen5Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Imagen5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imagen5ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Imagen5Button);
        Imagen5Button.setBounds(500, 160, 64, 64);

        Imagen6Button.setBackground(new java.awt.Color(240, 255, 153));
        Imagen6Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/granja64.png"))); // NOI18N
        Imagen6Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Imagen6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imagen6ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Imagen6Button);
        Imagen6Button.setBounds(500, 230, 64, 64);

        Imagen7Button.setBackground(new java.awt.Color(240, 255, 153));
        Imagen7Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pluma64.png"))); // NOI18N
        Imagen7Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Imagen7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imagen7ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Imagen7Button);
        Imagen7Button.setBounds(500, 300, 64, 64);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarButtonActionPerformed
        if(vez == 1){
        reproductor.stop();
        }
        vez=0;
        stopSound();
        //boton para volver al menu principal, se declara tamaño y al centro
        MainMenu Menu = new MainMenu();
        Menu.setSize(909, 655);
        Menu.setLocationRelativeTo(null);
        Menu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_RegresarButtonActionPerformed

    private void ConfiguracionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfiguracionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfiguracionButtonActionPerformed

    private void Cancion3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancion3ButtonActionPerformed
        if(vez == 1){
        reproductor.stop();
        }
        vez=0;
        stopSound();
        //boton para volver al menu principal, se declara tamaño y al centro
        CancionMaria Cancion = new CancionMaria();
        Cancion.setSize(909, 655);
        Cancion.setLocationRelativeTo(null);
        Cancion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Cancion3ButtonActionPerformed

    private void Cancion6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancion6ButtonActionPerformed
        if(vez == 1){
        reproductor.stop();
        }
        vez=0;
        stopSound();
        //boton para volver al menu principal, se declara tamaño y al centro
        CancionGranja Cancion = new CancionGranja();
        Cancion.setSize(909, 655);
        Cancion.setLocationRelativeTo(null);
        Cancion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Cancion6ButtonActionPerformed

    private void PlayAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayAllButtonActionPerformed
        //Reproductor de audio
            if(vez==0){   
            try{
                stopSound();
                urlArchivoMusica = new URL("file:"+"src/sonidos/playAll.wav");//url del archivo a reproducir
                reproductor = Manager.createRealizedPlayer(urlArchivoMusica);
                Component controles = reproductor.getControlPanelComponent();
                if(controles != null){
                this.add(controles);
                //controles.setLocation(0,185);
                //controles.setSize(360, 50);
                jPanel1.add(controles);
                }
                reproductor.start();
                }catch(Exception e){
                System.out.println("se encontró un error al intentar reproducir el archivo");
                }
            vez = 1;
            }else{
                    reproductor.stop();
                    vez=0;
                    }
    }//GEN-LAST:event_PlayAllButtonActionPerformed
    
    private void Imagen8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imagen8ButtonActionPerformed
        if(vez == 1){
        reproductor.stop();
        }
        vez=0;
        stopSound();
        playSound("Rema_tu_boteVoz");
    }//GEN-LAST:event_Imagen8ButtonActionPerformed

    private void Imagen1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imagen1ButtonActionPerformed
        if(vez == 1){
        reproductor.stop();
        }
        vez=0;
        stopSound();
        playSound("Estrellita_donde_estasVoz");
    }//GEN-LAST:event_Imagen1ButtonActionPerformed

    private void Imagen2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imagen2ButtonActionPerformed
        if(vez == 1){
        reproductor.stop();
        }
        vez=0;
        stopSound();
        playSound("Incy_Wincy_ArañaVoz");
    }//GEN-LAST:event_Imagen2ButtonActionPerformed

    private void Imagen3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imagen3ButtonActionPerformed
        if(vez == 1){
        reproductor.stop();
        }
        vez=0;
        stopSound();
        playSound("Maria_tiene_un_corderitoVoz");
    }//GEN-LAST:event_Imagen3ButtonActionPerformed

    private void Imagen4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imagen4ButtonActionPerformed
        if(vez == 1){
        reproductor.stop();
        }
        vez=0;
        stopSound();
        playSound("El_granjero_en_la_cañadaVoz");
    }//GEN-LAST:event_Imagen4ButtonActionPerformed

    private void Imagen5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imagen5ButtonActionPerformed
        if(vez == 1){
        reproductor.stop();
        }
        vez=0;
        stopSound();
        playSound("La_cancion_del_ABCVoz");
    }//GEN-LAST:event_Imagen5ButtonActionPerformed

    private void Imagen6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imagen6ButtonActionPerformed
        if(vez == 1){
        reproductor.stop();
        }
        vez=0;
        stopSound();
        playSound("El_viejo_mcdonaldVoz");
    }//GEN-LAST:event_Imagen6ButtonActionPerformed

    private void Imagen7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imagen7ButtonActionPerformed
        if(vez == 1){
        reproductor.stop();
        }
        vez=0;
        stopSound();
        playSound("Un_yankee_viajaVoz");
    }//GEN-LAST:event_Imagen7ButtonActionPerformed

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        if(vez == 1){
        reproductor.stop();
        }
        vez=0;
        stopSound();
        playSound("Elige_una_cancion");
    }//GEN-LAST:event_PlayButtonActionPerformed

    private void Cancion1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancion1ButtonActionPerformed
        if(vez == 1){
        reproductor.stop();
        }
        vez=0;
        stopSound();
        //boton para volver al menu principal, se declara tamaño y al centro
        CancionEstrellita Cancion = new CancionEstrellita();
        Cancion.setSize(909, 655);
        Cancion.setLocationRelativeTo(null);
        Cancion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Cancion1ButtonActionPerformed

    private void Cancion2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancion2ButtonActionPerformed
        if(vez == 1){
        reproductor.stop();
        }
        vez=0;
        stopSound();
        //boton para volver al menu principal, se declara tamaño y al centro
        CancionAraña Cancion = new CancionAraña();
        Cancion.setSize(909, 655);
        Cancion.setLocationRelativeTo(null);
        Cancion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Cancion2ButtonActionPerformed

    private void Cancion4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancion4ButtonActionPerformed
        if(vez == 1){
        reproductor.stop();
        }
        vez=0;
        stopSound();
        //boton para volver al menu principal, se declara tamaño y al centro
        CancionGranjero Cancion = new CancionGranjero();
        Cancion.setSize(909, 655);
        Cancion.setLocationRelativeTo(null);
        Cancion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Cancion4ButtonActionPerformed

    private void Cancion5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancion5ButtonActionPerformed
        if(vez == 1){
        reproductor.stop();
        }
        vez=0;
        stopSound();
        //boton para volver al menu principal, se declara tamaño y al centro
        CancionABC Cancion = new CancionABC();
        Cancion.setSize(909, 655);
        Cancion.setLocationRelativeTo(null);
        Cancion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Cancion5ButtonActionPerformed

    private void Cancion7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancion7ButtonActionPerformed
        if(vez == 1){
        reproductor.stop();
        }
        vez=0;
        stopSound();
        //boton para volver al menu principal, se declara tamaño y al centro
        CancionYankee Cancion = new CancionYankee();
        Cancion.setSize(909, 655);
        Cancion.setLocationRelativeTo(null);
        Cancion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Cancion7ButtonActionPerformed

    private void Cancion8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancion8ButtonActionPerformed
        if(vez == 1){
        reproductor.stop();
        }
        vez=0;
        stopSound();
        //boton para volver al menu principal, se declara tamaño y al centro
        CancionBote Cancion = new CancionBote();
        Cancion.setSize(909, 655);
        Cancion.setLocationRelativeTo(null);
        Cancion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Cancion8ButtonActionPerformed

     public void botonesTransparentes(){
        ConfiguracionButton.setOpaque(false);
        ConfiguracionButton.setContentAreaFilled(false);
        ConfiguracionButton.setBorderPainted(false);
        ConfiguracionButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ConfiguracionButton.setFocusPainted(false);
        RegresarButton.setOpaque(false);
        RegresarButton.setContentAreaFilled(false);
        RegresarButton.setBorderPainted(false);
        RegresarButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        RegresarButton.setFocusPainted(false);
        PlayAllButton.setOpaque(false);
        PlayAllButton.setContentAreaFilled(false);
        PlayAllButton.setBorderPainted(false);
        PlayAllButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        PlayAllButton.setFocusPainted(false);
        PlayButton.setOpaque(false);
        PlayButton.setContentAreaFilled(false);
        PlayButton.setBorderPainted(false);
        PlayButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        PlayButton.setFocusPainted(false);
        Cancion1Button.setOpaque(false);
        Cancion1Button.setContentAreaFilled(false);
        Cancion1Button.setBorderPainted(false);
        Cancion1Button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Cancion1Button.setFocusPainted(false);
        Cancion2Button.setOpaque(false);
        Cancion2Button.setContentAreaFilled(false);
        Cancion2Button.setBorderPainted(false);
        Cancion2Button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Cancion2Button.setFocusPainted(false);
        Cancion3Button.setOpaque(false);
        Cancion3Button.setContentAreaFilled(false);
        Cancion3Button.setBorderPainted(false);
        Cancion3Button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Cancion3Button.setFocusPainted(false);
        Cancion4Button.setOpaque(false);
        Cancion4Button.setContentAreaFilled(false);
        Cancion4Button.setBorderPainted(false);
        Cancion4Button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Cancion4Button.setFocusPainted(false);
        Cancion5Button.setOpaque(false);
        Cancion5Button.setContentAreaFilled(false);
        Cancion5Button.setBorderPainted(false);
        Cancion5Button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Cancion5Button.setFocusPainted(false);
        Cancion6Button.setOpaque(false);
        Cancion6Button.setContentAreaFilled(false);
        Cancion6Button.setBorderPainted(false);
        Cancion6Button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Cancion6Button.setFocusPainted(false);
        Cancion7Button.setOpaque(false);
        Cancion7Button.setContentAreaFilled(false);
        Cancion7Button.setBorderPainted(false);
        Cancion7Button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Cancion7Button.setFocusPainted(false);
        Cancion8Button.setOpaque(false);
        Cancion8Button.setContentAreaFilled(false);
        Cancion8Button.setBorderPainted(false);
        Cancion8Button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Cancion8Button.setFocusPainted(false);
        Imagen1Button.setBorderPainted(false);
        Imagen1Button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Imagen2Button.setBorderPainted(false);
        Imagen2Button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Imagen3Button.setBorderPainted(false);
        Imagen3Button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Imagen4Button.setBorderPainted(false);
        Imagen4Button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Imagen5Button.setBorderPainted(false);
        Imagen5Button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Imagen6Button.setBorderPainted(false);
        Imagen6Button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Imagen7Button.setBorderPainted(false);
        Imagen7Button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Imagen8Button.setBorderPainted(false);
        Imagen8Button.setCursor(new Cursor(Cursor.HAND_CURSOR));
 }
     
     private void playSound(String File) { // Play a wav file specified by fileName
        try {
            String path = "src/sonidos/" + File + ".wav";
            File file = new File(path);
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(file);
            clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (Exception e) {
        }
    }
    
    //metodo para detener el sonido
    private void stopSound() { // Play a wav file specified by fileName
        try {
            clip.stop();
        } catch (Exception e) {
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCanciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCanciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCanciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCanciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCanciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancion1Button;
    private javax.swing.JButton Cancion2Button;
    private javax.swing.JButton Cancion3Button;
    private javax.swing.JButton Cancion4Button;
    private javax.swing.JButton Cancion5Button;
    private javax.swing.JButton Cancion6Button;
    private javax.swing.JButton Cancion7Button;
    private javax.swing.JButton Cancion8Button;
    private javax.swing.JButton ConfiguracionButton;
    private javax.swing.JLabel EscucharTodosLabel;
    private javax.swing.JButton Imagen1Button;
    private javax.swing.JButton Imagen2Button;
    private javax.swing.JButton Imagen3Button;
    private javax.swing.JButton Imagen4Button;
    private javax.swing.JButton Imagen5Button;
    private javax.swing.JButton Imagen6Button;
    private javax.swing.JButton Imagen7Button;
    private javax.swing.JButton Imagen8Button;
    private javax.swing.JLabel LetrasDeAbajoLabel;
    private javax.swing.JLabel LetrasDeArribaLabel;
    private javax.swing.JButton PlayAllButton;
    private javax.swing.JButton PlayButton;
    private javax.swing.JButton RegresarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
