/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repasar;

import interfaces.*;
import complementos.TrasladadorPalabras;
import letras.LetraA;
import java.awt.Cursor;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JFrame;
import silabas.SilabaTaza;
/**
 *
 * @author Alberto Villarreal
 */
public class RepasarMenu extends javax.swing.JFrame {
        //Recalcar el tamaño de la interfaz
	private final int WINDOW_WIDTH = 909;
	private final int WINDOW_HEIGHT = 655;
    /**
     * Creates new form FabricaDePalabras
     */
    public RepasarMenu() {
        initComponents();
                //botonesTransparentes(); //manda a llamar al metodo botonesTransparentes
                botonesTransparentes();
                //this.setLocationRelativeTo(null); //Para que apareza la interfaz en el centro
		// Set window size.
		setSize(WINDOW_WIDTH, WINDOW_HEIGHT);
                setTitle("LEON"); //Titulo del programa
		setResizable(false); //Remueve el boton de maximizar pantalla
		// Specify what happens when close button is clicked.
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		panelLabel.setOpaque(true);
		// Generate an instance of the class that accesses
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ConfiguracionButton = new javax.swing.JButton();
        RegresarButton = new javax.swing.JButton();
        PlayButton = new javax.swing.JButton();
        BButton = new javax.swing.JButton();
        CButton = new javax.swing.JButton();
        ChButton = new javax.swing.JButton();
        EButton = new javax.swing.JButton();
        AButton = new javax.swing.JButton();
        DButton = new javax.swing.JButton();
        JButton = new javax.swing.JButton();
        FButton = new javax.swing.JButton();
        IButton = new javax.swing.JButton();
        KButton = new javax.swing.JButton();
        GButton = new javax.swing.JButton();
        HButton = new javax.swing.JButton();
        ÑButton = new javax.swing.JButton();
        LButton = new javax.swing.JButton();
        NButton = new javax.swing.JButton();
        OButton = new javax.swing.JButton();
        LlButton = new javax.swing.JButton();
        MButton = new javax.swing.JButton();
        SButton = new javax.swing.JButton();
        PButton = new javax.swing.JButton();
        RrButton = new javax.swing.JButton();
        TButton = new javax.swing.JButton();
        QButton = new javax.swing.JButton();
        RButton = new javax.swing.JButton();
        YButton = new javax.swing.JButton();
        UButton = new javax.swing.JButton();
        XButton = new javax.swing.JButton();
        ZButton = new javax.swing.JButton();
        VButton = new javax.swing.JButton();
        WButton = new javax.swing.JButton();
        EmpezarPrincipioButton = new javax.swing.JButton();
        PlayButton2 = new javax.swing.JButton();
        TituloLabel = new javax.swing.JLabel();
        panelLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 153));
        jPanel1.setLayout(null);

        ConfiguracionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuracion_6.png"))); // NOI18N
        ConfiguracionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfiguracionButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ConfiguracionButton);
        ConfiguracionButton.setBounds(0, 560, 60, 70);

        RegresarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar_2.png"))); // NOI18N
        RegresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RegresarButton);
        RegresarButton.setBounds(830, 560, 80, 70);

        PlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/play-bdutton2.png"))); // NOI18N
        jPanel1.add(PlayButton);
        PlayButton.setBounds(120, 190, 70, 70);

        BButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b_50.png"))); // NOI18N
        BButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BButton);
        BButton.setBounds(410, 90, 90, 90);

        CButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/c_50.png"))); // NOI18N
        CButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CButton);
        CButton.setBounds(500, 90, 90, 90);

        ChButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ch_50.png"))); // NOI18N
        ChButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ChButton);
        ChButton.setBounds(590, 90, 90, 90);

        EButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/e_50.png"))); // NOI18N
        EButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EButtonActionPerformed(evt);
            }
        });
        jPanel1.add(EButton);
        EButton.setBounds(770, 90, 90, 90);

        AButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a_50.png"))); // NOI18N
        AButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AButton);
        AButton.setBounds(320, 90, 90, 90);

        DButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/d_50.png"))); // NOI18N
        DButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DButton);
        DButton.setBounds(680, 90, 90, 90);

        JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/j_50.png"))); // NOI18N
        JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonActionPerformed(evt);
            }
        });
        jPanel1.add(JButton);
        JButton.setBounds(680, 180, 90, 90);

        FButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/f_50.png"))); // NOI18N
        FButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FButtonActionPerformed(evt);
            }
        });
        jPanel1.add(FButton);
        FButton.setBounds(320, 180, 90, 90);

        IButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/i_50.png"))); // NOI18N
        IButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IButtonActionPerformed(evt);
            }
        });
        jPanel1.add(IButton);
        IButton.setBounds(590, 180, 90, 90);

        KButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/k_50.png"))); // NOI18N
        KButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KButtonActionPerformed(evt);
            }
        });
        jPanel1.add(KButton);
        KButton.setBounds(770, 180, 90, 90);

        GButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/g_50.png"))); // NOI18N
        GButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GButtonActionPerformed(evt);
            }
        });
        jPanel1.add(GButton);
        GButton.setBounds(410, 180, 90, 90);

        HButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/h_50.png"))); // NOI18N
        HButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HButtonActionPerformed(evt);
            }
        });
        jPanel1.add(HButton);
        HButton.setBounds(500, 180, 90, 90);

        ÑButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/n_1_50.png"))); // NOI18N
        ÑButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ÑButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ÑButton);
        ÑButton.setBounds(680, 270, 90, 90);

        LButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/l_50.png"))); // NOI18N
        LButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LButton);
        LButton.setBounds(320, 270, 90, 90);

        NButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/n_50.png"))); // NOI18N
        NButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NButtonActionPerformed(evt);
            }
        });
        jPanel1.add(NButton);
        NButton.setBounds(590, 270, 90, 90);

        OButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/o_50.png"))); // NOI18N
        OButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OButtonActionPerformed(evt);
            }
        });
        jPanel1.add(OButton);
        OButton.setBounds(770, 270, 90, 90);

        LlButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ll_50.png"))); // NOI18N
        LlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LlButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LlButton);
        LlButton.setBounds(410, 270, 90, 90);

        MButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m_50.png"))); // NOI18N
        MButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MButtonActionPerformed(evt);
            }
        });
        jPanel1.add(MButton);
        MButton.setBounds(500, 270, 90, 90);

        SButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/s_50.png"))); // NOI18N
        SButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SButton);
        SButton.setBounds(680, 360, 90, 90);

        PButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/p_50.png"))); // NOI18N
        PButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PButton);
        PButton.setBounds(320, 360, 90, 90);

        RrButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rr_50.png"))); // NOI18N
        RrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RrButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RrButton);
        RrButton.setBounds(590, 360, 90, 90);

        TButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/t_50.png"))); // NOI18N
        TButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TButtonActionPerformed(evt);
            }
        });
        jPanel1.add(TButton);
        TButton.setBounds(770, 360, 90, 90);

        QButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/q_50.png"))); // NOI18N
        QButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QButtonActionPerformed(evt);
            }
        });
        jPanel1.add(QButton);
        QButton.setBounds(410, 360, 90, 90);

        RButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/r_50.png"))); // NOI18N
        RButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RButton);
        RButton.setBounds(500, 360, 90, 90);

        YButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/y_50.png"))); // NOI18N
        YButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YButtonActionPerformed(evt);
            }
        });
        jPanel1.add(YButton);
        YButton.setBounds(680, 450, 90, 90);

        UButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/u_50.png"))); // NOI18N
        UButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UButton);
        UButton.setBounds(320, 450, 90, 90);

        XButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x_50.png"))); // NOI18N
        XButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XButtonActionPerformed(evt);
            }
        });
        jPanel1.add(XButton);
        XButton.setBounds(590, 450, 90, 90);

        ZButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/z_50.png"))); // NOI18N
        ZButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ZButton);
        ZButton.setBounds(770, 450, 90, 90);

        VButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/v_50.png"))); // NOI18N
        VButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VButtonActionPerformed(evt);
            }
        });
        jPanel1.add(VButton);
        VButton.setBounds(410, 450, 90, 90);

        WButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/w_50.png"))); // NOI18N
        WButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WButtonActionPerformed(evt);
            }
        });
        jPanel1.add(WButton);
        WButton.setBounds(500, 450, 90, 90);

        EmpezarPrincipioButton.setBackground(new java.awt.Color(102, 255, 255));
        EmpezarPrincipioButton.setFont(new java.awt.Font("Smart Kid", 1, 24)); // NOI18N
        EmpezarPrincipioButton.setText("<html>Empezar desde <br/><center> el principio</center> <br/></html>");
        EmpezarPrincipioButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        EmpezarPrincipioButton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        EmpezarPrincipioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpezarPrincipioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(EmpezarPrincipioButton);
        EmpezarPrincipioButton.setBounds(60, 280, 190, 80);

        PlayButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/play-bdutton2.png"))); // NOI18N
        jPanel1.add(PlayButton2);
        PlayButton2.setBounds(550, 0, 70, 70);

        TituloLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        TituloLabel.setText("Repaso de Letras");
        jPanel1.add(TituloLabel);
        TituloLabel.setBounds(10, 0, 410, 41);

        panelLabel.setBackground(new java.awt.Color(153, 153, 0));
        panelLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.add(panelLabel);
        panelLabel.setBounds(310, 80, 560, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConfiguracionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfiguracionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfiguracionButtonActionPerformed

    private void RegresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarButtonActionPerformed
        //boton para volver al menu principal, se declara tamaño y al centro
        FabricaDePalabras Pal = new FabricaDePalabras();
        Pal.setSize(909, 655);
        Pal.setLocationRelativeTo(null);
        Pal.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_RegresarButtonActionPerformed

    private void BButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BButtonActionPerformed
        RepasarB B = new RepasarB();
        B.setSize(909, 655);
        B.setLocationRelativeTo(null);
        B.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BButtonActionPerformed

    private void CButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CButtonActionPerformed
        RepasarC C = new RepasarC();
        C.setSize(909, 655);
        C.setLocationRelativeTo(null);
        C.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CButtonActionPerformed

    private void ChButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChButtonActionPerformed
        RepasarCh Ch = new RepasarCh();
        Ch.setSize(909, 655);
        Ch.setLocationRelativeTo(null);
        Ch.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ChButtonActionPerformed

    private void EButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonActionPerformed
        RepasarE E = new RepasarE();
        E.setSize(909, 655);
        E.setLocationRelativeTo(null);
        E.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EButtonActionPerformed

    private void AButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonActionPerformed
        RepasarA A = new RepasarA();
        A.setSize(909, 655);
        A.setLocationRelativeTo(null);
        A.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AButtonActionPerformed

    private void DButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DButtonActionPerformed
        RepasarD D = new RepasarD();
        D.setSize(909, 655);
        D.setLocationRelativeTo(null);
        D.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DButtonActionPerformed

    private void JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonActionPerformed
        RepasarJ J = new RepasarJ();
        J.setSize(909, 655);
        J.setLocationRelativeTo(null);
        J.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JButtonActionPerformed

    private void FButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FButtonActionPerformed
        RepasarF F = new RepasarF();
        F.setSize(909, 655);
        F.setLocationRelativeTo(null);
        F.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FButtonActionPerformed

    private void IButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IButtonActionPerformed
        RepasarI I = new RepasarI();
        I.setSize(909, 655);
        I.setLocationRelativeTo(null);
        I.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IButtonActionPerformed

    private void KButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KButtonActionPerformed
        RepasarK K = new RepasarK();
        K.setSize(909, 655);
        K.setLocationRelativeTo(null);
        K.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KButtonActionPerformed

    private void GButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GButtonActionPerformed
       RepasarG G = new RepasarG();
        G.setSize(909, 655);
        G.setLocationRelativeTo(null);
        G.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GButtonActionPerformed

    private void HButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HButtonActionPerformed
        RepasarH H = new RepasarH();
        H.setSize(909, 655);
        H.setLocationRelativeTo(null);
        H.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HButtonActionPerformed

    private void ÑButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ÑButtonActionPerformed
        RepasarÑ Ñ = new RepasarÑ();
        Ñ.setSize(909, 655);
        Ñ.setLocationRelativeTo(null);
        Ñ.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ÑButtonActionPerformed

    private void LButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButtonActionPerformed
        RepasarL L = new RepasarL();
        L.setSize(909, 655);
        L.setLocationRelativeTo(null);
        L.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LButtonActionPerformed

    private void NButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NButtonActionPerformed
        RepasarN N = new RepasarN();
        N.setSize(909, 655);
        N.setLocationRelativeTo(null);
        N.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NButtonActionPerformed

    private void OButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OButtonActionPerformed
        RepasarO O = new RepasarO();
        O.setSize(909, 655);
        O.setLocationRelativeTo(null);
        O.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_OButtonActionPerformed

    private void LlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LlButtonActionPerformed
        RepasarLl Ll = new RepasarLl();
        Ll.setSize(909, 655);
        Ll.setLocationRelativeTo(null);
        Ll.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LlButtonActionPerformed

    private void MButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MButtonActionPerformed
        RepasarM M = new RepasarM();
        M.setSize(909, 655);
        M.setLocationRelativeTo(null);
        M.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MButtonActionPerformed

    private void SButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SButtonActionPerformed
        RepasarS S = new RepasarS();
        S.setSize(909, 655);
        S.setLocationRelativeTo(null);
        S.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SButtonActionPerformed

    private void PButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PButtonActionPerformed
        RepasarP P = new RepasarP();
        P.setSize(909, 655);
        P.setLocationRelativeTo(null);
        P.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PButtonActionPerformed

    private void RrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RrButtonActionPerformed
        RepasarRr Rr = new RepasarRr();
        Rr.setSize(909, 655);
        Rr.setLocationRelativeTo(null);
        Rr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RrButtonActionPerformed

    private void TButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TButtonActionPerformed
        RepasarT T = new RepasarT();
        T.setSize(909, 655);
        T.setLocationRelativeTo(null);
        T.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TButtonActionPerformed

    private void QButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QButtonActionPerformed
        RepasarQ Q = new RepasarQ();
        Q.setSize(909, 655);
        Q.setLocationRelativeTo(null);
        Q.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_QButtonActionPerformed

    private void RButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RButtonActionPerformed
        RepasarR R = new RepasarR();
        R.setSize(909, 655);
        R.setLocationRelativeTo(null);
        R.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RButtonActionPerformed

    private void YButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YButtonActionPerformed
        RepasarY Y = new RepasarY();
        Y.setSize(909, 655);
        Y.setLocationRelativeTo(null);
        Y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_YButtonActionPerformed

    private void UButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UButtonActionPerformed
        RepasarU U = new RepasarU();
        U.setSize(909, 655);
        U.setLocationRelativeTo(null);
        U.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UButtonActionPerformed

    private void XButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XButtonActionPerformed
        RepasarX X = new RepasarX();
        X.setSize(909, 655);
        X.setLocationRelativeTo(null);
        X.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_XButtonActionPerformed

    private void ZButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZButtonActionPerformed
        RepasarZ Z = new RepasarZ();
        Z.setSize(909, 655);
        Z.setLocationRelativeTo(null);
        Z.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ZButtonActionPerformed

    private void VButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VButtonActionPerformed
        RepasarV V = new RepasarV();
        V.setSize(909, 655);
        V.setLocationRelativeTo(null);
        V.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VButtonActionPerformed

    private void WButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WButtonActionPerformed
        RepasarW W = new RepasarW();
        W.setSize(909, 655);
        W.setLocationRelativeTo(null);
        W.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_WButtonActionPerformed

    private void EmpezarPrincipioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpezarPrincipioButtonActionPerformed
        RepasarA A = new RepasarA();
        A.setSize(909, 655);
        A.setLocationRelativeTo(null);
        A.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EmpezarPrincipioButtonActionPerformed

     public void botonesTransparentes(){
        ConfiguracionButton.setOpaque(false);
        ConfiguracionButton.setContentAreaFilled(false);
        ConfiguracionButton.setBorderPainted(false);
        ConfiguracionButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ConfiguracionButton.setFocusPainted(false);
        RegresarButton.setOpaque(false);
        RegresarButton.setContentAreaFilled(false);
        RegresarButton.setBorderPainted(false);
        RegresarButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        RegresarButton.setFocusPainted(false);
        PlayButton.setOpaque(false);
        PlayButton.setContentAreaFilled(false);
        PlayButton.setBorderPainted(false);
        PlayButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        PlayButton.setFocusPainted(false);
        PlayButton2.setContentAreaFilled(false);
        PlayButton2.setBorderPainted(false);
        PlayButton2.setCursor(new Cursor(Cursor.HAND_CURSOR));
        PlayButton2.setFocusPainted(false);
        EmpezarPrincipioButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        EmpezarPrincipioButton.setFocusPainted(false);
        AButton.setOpaque(false);
        AButton.setContentAreaFilled(false);
        AButton.setBorderPainted(false);
        AButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        AButton.setFocusPainted(false);
        BButton.setOpaque(false);
        BButton.setContentAreaFilled(false);
        BButton.setBorderPainted(false);
        BButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        BButton.setFocusPainted(false);
        CButton.setOpaque(false);
        CButton.setContentAreaFilled(false);
        CButton.setBorderPainted(false);
        CButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        CButton.setFocusPainted(false);
        ChButton.setOpaque(false);
        ChButton.setContentAreaFilled(false);
        ChButton.setBorderPainted(false);
        ChButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ChButton.setFocusPainted(false);
        DButton.setOpaque(false);
        DButton.setContentAreaFilled(false);
        DButton.setBorderPainted(false);
        DButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        DButton.setFocusPainted(false);
        EButton.setOpaque(false);
        EButton.setContentAreaFilled(false);
        EButton.setBorderPainted(false);
        EButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        EButton.setFocusPainted(false);
        FButton.setOpaque(false);
        FButton.setContentAreaFilled(false);
        FButton.setBorderPainted(false);
        FButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        FButton.setFocusPainted(false);
        GButton.setOpaque(false);
        GButton.setContentAreaFilled(false);
        GButton.setBorderPainted(false);
        GButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        GButton.setFocusPainted(false);
        HButton.setOpaque(false);
        HButton.setContentAreaFilled(false);
        HButton.setBorderPainted(false);
        HButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        HButton.setFocusPainted(false);
        IButton.setOpaque(false);
        IButton.setContentAreaFilled(false);
        IButton.setBorderPainted(false);
        IButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        IButton.setFocusPainted(false);
        JButton.setOpaque(false);
        JButton.setContentAreaFilled(false);
        JButton.setBorderPainted(false);
        JButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        JButton.setFocusPainted(false);
        KButton.setOpaque(false);
        KButton.setContentAreaFilled(false);
        KButton.setBorderPainted(false);
        KButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        KButton.setFocusPainted(false);
        LButton.setOpaque(false);
        LButton.setContentAreaFilled(false);
        LButton.setBorderPainted(false);
        LButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        LButton.setFocusPainted(false);
        LlButton.setOpaque(false);
        LlButton.setContentAreaFilled(false);
        LlButton.setBorderPainted(false);
        LlButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        LlButton.setFocusPainted(false);
        MButton.setOpaque(false);
        MButton.setContentAreaFilled(false);
        MButton.setBorderPainted(false);
        MButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        MButton.setFocusPainted(false);
        NButton.setOpaque(false);
        NButton.setContentAreaFilled(false);
        NButton.setBorderPainted(false);
        NButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        NButton.setFocusPainted(false);
        ÑButton.setOpaque(false);
        ÑButton.setContentAreaFilled(false);
        ÑButton.setBorderPainted(false);
        ÑButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ÑButton.setFocusPainted(false);
        OButton.setOpaque(false);
        OButton.setContentAreaFilled(false);
        OButton.setBorderPainted(false);
        OButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        OButton.setFocusPainted(false);
        PButton.setOpaque(false);
        PButton.setContentAreaFilled(false);
        PButton.setBorderPainted(false);
        PButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        PButton.setFocusPainted(false);
        QButton.setOpaque(false);
        QButton.setContentAreaFilled(false);
        QButton.setBorderPainted(false);
        QButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        QButton.setFocusPainted(false);
        RButton.setOpaque(false);
        RButton.setContentAreaFilled(false);
        RButton.setBorderPainted(false);
        RButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        RButton.setFocusPainted(false);
        RrButton.setOpaque(false);
        RrButton.setContentAreaFilled(false);
        RrButton.setBorderPainted(false);
        RrButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        RrButton.setFocusPainted(false);
        SButton.setOpaque(false);
        SButton.setContentAreaFilled(false);
        SButton.setBorderPainted(false);
        SButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        SButton.setFocusPainted(false);
        TButton.setOpaque(false);
        TButton.setContentAreaFilled(false);
        TButton.setBorderPainted(false);
        TButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        TButton.setFocusPainted(false);
        UButton.setOpaque(false);
        UButton.setContentAreaFilled(false);
        UButton.setBorderPainted(false);
        UButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        UButton.setFocusPainted(false);
        VButton.setOpaque(false);
        VButton.setContentAreaFilled(false);
        VButton.setBorderPainted(false);
        VButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        VButton.setFocusPainted(false);
        WButton.setOpaque(false);
        WButton.setContentAreaFilled(false);
        WButton.setBorderPainted(false);
        WButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        WButton.setFocusPainted(false);
        XButton.setOpaque(false);
        XButton.setContentAreaFilled(false);
        XButton.setBorderPainted(false);
        XButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        XButton.setFocusPainted(false);
        YButton.setOpaque(false);
        YButton.setContentAreaFilled(false);
        YButton.setBorderPainted(false);
        YButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        YButton.setFocusPainted(false);
        ZButton.setOpaque(false);
        ZButton.setContentAreaFilled(false);
        ZButton.setBorderPainted(false);
        ZButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ZButton.setFocusPainted(false);
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RepasarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RepasarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RepasarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RepasarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RepasarMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AButton;
    private javax.swing.JButton BButton;
    private javax.swing.JButton CButton;
    private javax.swing.JButton ChButton;
    private javax.swing.JButton ConfiguracionButton;
    private javax.swing.JButton DButton;
    private javax.swing.JButton EButton;
    private javax.swing.JButton EmpezarPrincipioButton;
    private javax.swing.JButton FButton;
    private javax.swing.JButton GButton;
    private javax.swing.JButton HButton;
    private javax.swing.JButton IButton;
    private javax.swing.JButton JButton;
    private javax.swing.JButton KButton;
    private javax.swing.JButton LButton;
    private javax.swing.JButton LlButton;
    private javax.swing.JButton MButton;
    private javax.swing.JButton NButton;
    private javax.swing.JButton OButton;
    private javax.swing.JButton PButton;
    private javax.swing.JButton PlayButton;
    private javax.swing.JButton PlayButton2;
    private javax.swing.JButton QButton;
    private javax.swing.JButton RButton;
    private javax.swing.JButton RegresarButton;
    private javax.swing.JButton RrButton;
    private javax.swing.JButton SButton;
    private javax.swing.JButton TButton;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JButton UButton;
    private javax.swing.JButton VButton;
    private javax.swing.JButton WButton;
    private javax.swing.JButton XButton;
    private javax.swing.JButton YButton;
    private javax.swing.JButton ZButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel panelLabel;
    private javax.swing.JButton ÑButton;
    // End of variables declaration//GEN-END:variables
}
