/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teclado;

import palabras.*;
import silabas.*;
import letras.*;
import complementos.CalculaCalificacion;
import interfaces.FabricaDePalabras;
import interfaces.MainMenu;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.Random;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * ************************
 * /**
 *
 * @author Alberto Villarreal
 */
public class CalificacionTeclado extends javax.swing.JFrame {
    //Recalcar el tamaño de la interfaz

    private final int WINDOW_WIDTH = 909;
    private final int WINDOW_HEIGHT = 655;
    private int valor;

    /**
     * Creates new form Letras
     */
    public CalificacionTeclado() {
        initComponents();
        botonesTransparentes(); //manda a llamar al metodo botonesTransparentes
        // this.setLocationRelativeTo(null); //Para que apareza la interfaz en el centro
        // Set window size.
        setSize(WINDOW_WIDTH, WINDOW_HEIGHT);
        setTitle("LEON");
        setResizable(false); //Remueve el boton de maximizar pantalla

        // Specify what happens when close button is clicked.
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        CalculaCalificacion Calificacion = new CalculaCalificacion();
        Calificacion.Formula();
        CalculaCalificacion Letras = new CalculaCalificacion();
        //Letras.PuntoFinal();   
        //if(Letras.getValue() == 30){
        //LetrasRepasarLabel.setText("Ninguna");
        //}else{
        //LetrasRepasarLabel.setText(Letras.getAr());
        //}
        System.out.println(Letras.getAr());
        NumeroCalifLabel.setText(Integer.toString(Calificacion.getCalificacion()));
        if(Calificacion.getCalificacion() >= 60){
        MensajeLabel2.setText("¡FELICIDADES!");
        }else if(Calificacion.getCalificacion() < 60 && Calificacion.getCalificacion() >= 40){
        MensajeLabel2.setText("¡CONTNIUA ASÍ!");
        MensajeLabel1.setText("Estás muy cerca");
        }else{
        MensajeLabel2.setText("¡NO TE RINDAS!");
        MensajeLabel1.setText("Sigue probando");
    }    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ConfiguracionButton = new javax.swing.JButton();
        SalirButton = new javax.swing.JButton();
        PlayButton = new javax.swing.JButton();
        NumeroCalifLabel = new javax.swing.JLabel();
        Confeti1 = new javax.swing.JLabel();
        Confeti2Label = new javax.swing.JLabel();
        MensajeLabel2 = new javax.swing.JLabel();
        CalificacionLabel = new javax.swing.JLabel();
        NotaLetrasLabel = new javax.swing.JLabel();
        MensajeLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(null);

        ConfiguracionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuracion_6.png"))); // NOI18N
        ConfiguracionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfiguracionButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ConfiguracionButton);
        ConfiguracionButton.setBounds(0, 560, 60, 70);

        SalirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aprobado.png"))); // NOI18N
        SalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SalirButton);
        SalirButton.setBounds(420, 560, 70, 70);

        PlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/play-bdutton2.png"))); // NOI18N
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PlayButton);
        PlayButton.setBounds(800, 560, 70, 70);

        NumeroCalifLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 48)); // NOI18N
        jPanel1.add(NumeroCalifLabel);
        NumeroCalifLabel.setBounds(620, 360, 120, 100);

        Confeti1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/confetti (1).png"))); // NOI18N
        Confeti1.setToolTipText("");
        jPanel1.add(Confeti1);
        Confeti1.setBounds(20, 0, 330, 280);

        Confeti2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/confetti (2).png"))); // NOI18N
        jPanel1.add(Confeti2Label);
        Confeti2Label.setBounds(620, 0, 310, 280);

        MensajeLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        MensajeLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.add(MensajeLabel2);
        MensajeLabel2.setBounds(320, 150, 300, 70);

        CalificacionLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 48)); // NOI18N
        CalificacionLabel.setText("Tu calificación es:");
        jPanel1.add(CalificacionLabel);
        CalificacionLabel.setBounds(190, 360, 550, 100);

        NotaLetrasLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        NotaLetrasLabel.setText("Ya pasaron 30 ejercicios");
        jPanel1.add(NotaLetrasLabel);
        NotaLetrasLabel.setBounds(310, 350, 300, 30);

        MensajeLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        MensajeLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.add(MensajeLabel1);
        MensajeLabel1.setBounds(320, 90, 280, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfiguracionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfiguracionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfiguracionButtonActionPerformed

    private void SalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirButtonActionPerformed
        ReseteaPreguntas();
        ReseteaLetras();
        ResetAciertos();
        MainMenu Menu = new MainMenu();
        Menu.setSize(909, 655);
        Menu.setLocationRelativeTo(null);
        Menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SalirButtonActionPerformed

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        playSound("a");
    }//GEN-LAST:event_PlayButtonActionPerformed

    public void botonesTransparentes() {
        ConfiguracionButton.setOpaque(false);
        ConfiguracionButton.setContentAreaFilled(false);
        ConfiguracionButton.setBorderPainted(false);
        ConfiguracionButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ConfiguracionButton.setFocusPainted(false);
        SalirButton.setOpaque(false);
        SalirButton.setContentAreaFilled(false);
        SalirButton.setBorderPainted(false);
        SalirButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        SalirButton.setFocusPainted(false);
        PlayButton.setOpaque(false);
        PlayButton.setContentAreaFilled(false);
        PlayButton.setBorderPainted(false);
        PlayButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        PlayButton.setFocusPainted(false);
    }
    
    //Metodo para resetear los aciertos
    public void ReseteaPreguntas(){ 
        CalculaCalificacion Preguntas = new CalculaCalificacion();
            Preguntas.ResetPreguntas();
    }
    
    public void ResetAciertos(){
         CalculaCalificacion Aciertos = new CalculaCalificacion();
            Aciertos.Reset();
    }
    
    public void ReseteaLetras(){
        CalculaCalificacion Letras = new CalculaCalificacion(); //Objeto para regresar el valor de letras a ninguno
                Letras.ResetLetras();
    }
    
    private void playSound(String File) { // Play a wav file specified by fileName
        try {
            String path = "src/sonidos/" + File + ".wav";
            File file = new File(path);
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(file);
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (Exception e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalificacionTeclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalificacionTeclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalificacionTeclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalificacionTeclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalificacionTeclado().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CalificacionLabel;
    private javax.swing.JLabel Confeti1;
    private javax.swing.JLabel Confeti2Label;
    private javax.swing.JButton ConfiguracionButton;
    private javax.swing.JLabel MensajeLabel1;
    private javax.swing.JLabel MensajeLabel2;
    private javax.swing.JLabel NotaLetrasLabel;
    private javax.swing.JLabel NumeroCalifLabel;
    private javax.swing.JButton PlayButton;
    private javax.swing.JButton SalirButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
