/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teclado;

import palabras.*;
import complementos.CalculaCalificacion;
import complementos.TrasladadorTeclado;
import interfaces.MainMenu;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.Random;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 * ************************
 * /**
 *
 * @author Alberto Villarreal
 */
public class TecladoDurazno extends javax.swing.JFrame {
    //Recalcar el tamaño de la interfaz

    private final int WINDOW_WIDTH = 909;
    private final int WINDOW_HEIGHT = 655;
    private JPanel panel;
    private int valor;
    private int restadas = 0;
    private int a = 0;
    private int pista = 0;
    public Clip clip;
    /**
     * Creates new form Letras
     */
    public TecladoDurazno() {
        initComponents();
        botonesTransparentes(); //manda a llamar al metodo botonesTransparentes
        // this.setLocationRelativeTo(null); //Para que apareza la interfaz en el centro
        // Set window size.
        setSize(WINDOW_WIDTH, WINDOW_HEIGHT);
        setTitle("LEON");
        setResizable(false); //Remueve el boton de maximizar pantalla

        // Specify what happens when close button is clicked.
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        NextButton.setVisible(false);
        PistaButton.setVisible(false);
        //metodo para ejecutar despues de 20 segundos, hace visible el boton de pista y el de salto
        Timer timer = new Timer(20000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent arg0) {
        NextButton.setVisible(true);
        PistaButton.setVisible(true);
        }
        });
        timer.setRepeats(false); // Only execute once
        timer.start(); // Go go go!
        
        
        
        playSound("Du-raz-no"); //1=letra a
        ImagenLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/durazno_silabas.png")));
        
//}
//}
//
//for (int i = 0; i < letters.length; i++){
//        
//    }
//if(letters[i]) = ""){
//}
//for (String s : new ArrayList<String>(list))     
//{
        //  list.add("u");
//}

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ConfiguracionButton = new javax.swing.JButton();
        SalirButton = new javax.swing.JButton();
        NextButton = new javax.swing.JButton();
        InstruccionLabel = new javax.swing.JLabel();
        ImagenLabel = new javax.swing.JLabel();
        RespuestaTextField = new javax.swing.JTextField();
        PlayButton = new javax.swing.JButton();
        CheckButton = new javax.swing.JButton();
        PistaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(null);

        ConfiguracionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuracion_6.png"))); // NOI18N
        ConfiguracionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfiguracionButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ConfiguracionButton);
        ConfiguracionButton.setBounds(0, 560, 60, 70);

        SalirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        SalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SalirButton);
        SalirButton.setBounds(830, 560, 80, 70);

        NextButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alberto Villarreal\\Downloads\\Tareas de Facultad\\Quinto Semestre\\Proyecto IHC\\Proyecto LEON\\LEON\\src\\imagenes\\next_arrow.png")); // NOI18N
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });
        jPanel1.add(NextButton);
        NextButton.setBounds(620, 250, 160, 128);

        InstruccionLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        InstruccionLabel.setText("Escribe la palabra que escuches");
        jPanel1.add(InstruccionLabel);
        InstruccionLabel.setBounds(240, 20, 470, 40);
        jPanel1.add(ImagenLabel);
        ImagenLabel.setBounds(300, 160, 310, 310);

        RespuestaTextField.setFont(new java.awt.Font("Smart Kid", 0, 48)); // NOI18N
        RespuestaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RespuestaTextField.setToolTipText("");
        RespuestaTextField.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray));
        RespuestaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespuestaTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(RespuestaTextField);
        RespuestaTextField.setBounds(240, 500, 426, 65);

        PlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/play-bdutton2.png"))); // NOI18N
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PlayButton);
        PlayButton.setBounds(420, 70, 70, 70);

        CheckButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aprobado.png"))); // NOI18N
        CheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CheckButton);
        CheckButton.setBounds(670, 502, 60, 60);

        PistaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pista.png"))); // NOI18N
        PistaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PistaButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PistaButton);
        PistaButton.setBounds(110, 440, 128, 128);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfiguracionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfiguracionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfiguracionButtonActionPerformed

    private void SalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirButtonActionPerformed
        stopSound();
//Atributos de los botones del JOptionPane        
        JButton button = new JButton();
        button.setContentAreaFilled(false);
        button.setBorderPainted(false);
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        button.setFocusPainted(false);
        button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aprobado.png")));
//button.setBackground(Color.BLACK);
//button.setForeground(Color.WHITE);

        JButton button2 = new JButton();
        button2.setContentAreaFilled(false);
        button2.setBorderPainted(false);
        button2.setCursor(new Cursor(Cursor.HAND_CURSOR));
        button2.setFocusPainted(false);
        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png")));
//button2.setBackground(Color.BLACK);
//button2.setForeground(Color.WHITE);

//Metodo para cuando se oprima el boton de confirmacion de salir
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                CalculaCalificacion Aciertos = new CalculaCalificacion(); //Objeto para regresar el valor de aciertos a 0
                Aciertos.Reset();
                Aciertos.ResetPreguntas();
                MainMenu Menu = new MainMenu();
                Menu.setSize(909, 655);
                Menu.setLocationRelativeTo(null);
                Menu.setVisible(true);
                JOptionPane.getRootFrame().dispose();
                dispose();
            }
        });

//Metodo para cancelar el boton de querer salir
        button2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                JOptionPane.getRootFrame().dispose();
            }
        });
//Declaramos los botones que se van a usar en el cuadro de dialogo
        JButton[] buttons = {button, button2};
        JOptionPane.showOptionDialog(null, "    ¿Quieres regresar al menú principal?", "Volver", JOptionPane.YES_NO_OPTION, JOptionPane.DEFAULT_OPTION, null, buttons, buttons[0]);
    }//GEN-LAST:event_SalirButtonActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        stopSound();
        CalculaCalificacion Preguntas = new CalculaCalificacion();
        Preguntas.CalcularPreguntas();
        System.out.println(Preguntas.getPreguntas());
        RespuestaTextField.setText("Durazno");
        Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent arg0) {
        TrasladadorTeclado Siguiente = new TrasladadorTeclado();
        Siguiente.CompararTeclado();
        dispose();
        }
        });
        timer.setRepeats(false); // Only execute once
        timer.start(); // Go go go!        
    }//GEN-LAST:event_NextButtonActionPerformed

    private void RespuestaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespuestaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RespuestaTextFieldActionPerformed

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        playSound("Du-raz-no");
    }//GEN-LAST:event_PlayButtonActionPerformed

    private void CheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckButtonActionPerformed
           stopSound();
            String respuesta = RespuestaTextField.getText();
           if("".equals(respuesta)){
           System.out.println("no se ha ingresado un String aun");
           }else{
           String respuesta_mayuscula = respuesta.substring(0,1).toUpperCase() + respuesta.substring(1).toLowerCase(); //transforma la primera letra en mayus, y la segunda en minus
           if("Durazno".equals(respuesta_mayuscula)){
           System.out.println("Correcto");
           playSound("correct");
            //Objeto para incrementar el numero de aciertos
            CalculaCalificacion Aciertos = new CalculaCalificacion();
            Aciertos.Calcular();
            CalculaCalificacion Preguntas = new CalculaCalificacion();
            Preguntas.CalcularPreguntas();
            System.out.println(Preguntas.getPreguntas());
            //Atributos de los botones del JOptionPane        
        JButton button = new JButton();
        button.setContentAreaFilled(false);
        button.setBorderPainted(false);
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        button.setFocusPainted(false);
        button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aprobado.png")));
//button.setBackground(Color.BLACK);
//button.setForeground(Color.WHITE);
            
//Metodo para cuando se oprima el boton de confirmacion de salir
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                stopSound();
                a=1;
                if(Aciertos.getPreguntas() == 30){
                CalificacionTeclado CalTec = new CalificacionTeclado();
                CalTec.setSize(909, 655);
                CalTec.setLocationRelativeTo(null);
                CalTec.setVisible(true);
                JOptionPane.getRootFrame().dispose();
                dispose();
                }
                else{
                //TrasladadorTeclado Siguiente = new TrasladadorTeclado();
                //Siguiente.CompararTeclado();
                TrasladadorTeclado Siguiente = new TrasladadorTeclado();
                Siguiente.CompararTeclado();
                JOptionPane.getRootFrame().dispose();
                dispose();
                }               
            }
        });

//Declaramos los botones que se van a usar en el cuadro de dialogo
        ImageIcon happyface = new ImageIcon("src/imagenes/happiness.png");
        JButton[] buttons = {button};
        int repeat = 1;
        for(int i=0; i<repeat; i++){
        JOptionPane.showOptionDialog(null, "     Respuesta correcta.", "¡Bien Hecho!", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, happyface, buttons, buttons[0]);
        //JOptionPane, por alguna razon su valor siempre sera -1, no importa lo que oprimas, cree una variable a=0, si se encuentra
        //en ese valor, repetirá el proceso, significando que no se ha seleccionado el boton correcto, al oprimir el boton correcto
        //el valor de a ahora es 1, por lo que deja de hacer iteraciones (repeat=0) y continua normalmente, todo con la finalidad
        //de que si se oprime el boton de exit "x" de la parte de arriba, se repita el JOptionPane.
            if( a == 0){
             repeat++;
            } else{
            repeat=0;
            }  
        }
           }else{
               playSound("TryAgain");
               System.out.println("prueba de nuevo");
               RespuestaTextField.setText(""); //el texto vuelve a la normalidad porque se equivocó
           }
           
           }
    }//GEN-LAST:event_CheckButtonActionPerformed

    private void PistaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PistaButtonActionPerformed
        stopSound();
        if (pista == 0){
        playSound("Ten_una_pista");
        System.out.println("Toma una pista");
        RespuestaTextField.setText("Duraz");
        }
        pista = 1;
    }//GEN-LAST:event_PistaButtonActionPerformed

    public void botonesTransparentes() {
        ConfiguracionButton.setOpaque(false);
        ConfiguracionButton.setContentAreaFilled(false);
        ConfiguracionButton.setBorderPainted(false);
        ConfiguracionButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ConfiguracionButton.setFocusPainted(false);
        SalirButton.setOpaque(false);
        SalirButton.setContentAreaFilled(false);
        SalirButton.setBorderPainted(false);
        SalirButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        SalirButton.setFocusPainted(false);
        PistaButton.setOpaque(false);
        PistaButton.setContentAreaFilled(false);
        PistaButton.setBorderPainted(false);
        PistaButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        PistaButton.setFocusPainted(false);
        PlayButton.setOpaque(false);
        PlayButton.setContentAreaFilled(false);
        PlayButton.setBorderPainted(false);
        PlayButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        PlayButton.setFocusPainted(false);
        NextButton.setOpaque(false);
        NextButton.setContentAreaFilled(false);
        NextButton.setBorderPainted(false);
        NextButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        NextButton.setFocusPainted(false);
        CheckButton.setOpaque(false);
        CheckButton.setContentAreaFilled(false);
        CheckButton.setBorderPainted(false);
        CheckButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        CheckButton.setFocusPainted(false);
    }

    private void playSound(String File) { // Play a wav file specified by fileName
        try {
            String path = "src/sonidos/" + File + ".wav";
            File file = new File(path);
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(file);
            clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (Exception e) {
        }
    }
    
    //metodo para detener el sonido
    private void stopSound() { // Play a wav file specified by fileName
        try {
            clip.stop();
        } catch (Exception e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TecladoDurazno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TecladoDurazno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TecladoDurazno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TecladoDurazno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TecladoDurazno().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckButton;
    private javax.swing.JButton ConfiguracionButton;
    private javax.swing.JLabel ImagenLabel;
    private javax.swing.JLabel InstruccionLabel;
    private javax.swing.JButton NextButton;
    private javax.swing.JButton PistaButton;
    private javax.swing.JButton PlayButton;
    private javax.swing.JTextField RespuestaTextField;
    private javax.swing.JButton SalirButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
