/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import complementos.TrasladadorPalabras;
import letras.LetraA;
import java.awt.Cursor;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JFrame;
import repasar.RepasarMenu;
import silabas.SilabaTaza;
/**
 *
 * @author Alberto Villarreal
 */
public class FabricaDePalabras extends javax.swing.JFrame {
        //Recalcar el tamaño de la interfaz
	private final int WINDOW_WIDTH = 909;
	private final int WINDOW_HEIGHT = 655;
        public Clip clip;
      //  public String path;
      //  public File file;
    /**
     * Creates new form FabricaDePalabras
     */
    public FabricaDePalabras() {
        initComponents();
                //botonesTransparentes(); //manda a llamar al metodo botonesTransparentes
                botonesTransparentes();
                //this.setLocationRelativeTo(null); //Para que apareza la interfaz en el centro
		// Set window size.
		setSize(WINDOW_WIDTH, WINDOW_HEIGHT);
                setTitle("LEON"); //Titulo del programa
		setResizable(false); //Remueve el boton de maximizar pantalla
		// Specify what happens when close button is clicked.
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		playSound("Fabrica_de_palabras");
		// Generate an instance of the class that accesses
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LetrasButton = new javax.swing.JButton();
        PalabrasButton = new javax.swing.JButton();
        SilabasButton = new javax.swing.JButton();
        ConfiguracionButton = new javax.swing.JButton();
        RegresarButton = new javax.swing.JButton();
        AlfabetoButton = new javax.swing.JButton();
        PlayButton = new javax.swing.JButton();
        PalabrasLabel = new javax.swing.JLabel();
        LetrasDeArribaLabel = new javax.swing.JLabel();
        LetrasDeAbajoLabel = new javax.swing.JLabel();
        LetrasLabel = new javax.swing.JLabel();
        SilabasLabel = new javax.swing.JLabel();
        Nivel1Label = new javax.swing.JLabel();
        Nivel2Label = new javax.swing.JLabel();
        Nivel3Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        LetrasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetrasButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LetrasButton);
        LetrasButton.setBounds(90, 150, 160, 160);

        PalabrasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PalabrasButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PalabrasButton);
        PalabrasButton.setBounds(640, 150, 160, 160);

        SilabasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SilabasButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SilabasButton);
        SilabasButton.setBounds(370, 290, 160, 160);

        ConfiguracionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuracion_6.png"))); // NOI18N
        ConfiguracionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfiguracionButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ConfiguracionButton);
        ConfiguracionButton.setBounds(0, 490, 60, 70);

        RegresarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar_2.png"))); // NOI18N
        RegresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RegresarButton);
        RegresarButton.setBounds(830, 490, 80, 70);

        AlfabetoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alfabeto_3.png"))); // NOI18N
        AlfabetoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlfabetoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AlfabetoButton);
        AlfabetoButton.setBounds(0, 70, 60, 60);

        PlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/play-bdutton2.png"))); // NOI18N
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PlayButton);
        PlayButton.setBounds(420, 80, 70, 70);

        PalabrasLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/palabras.png"))); // NOI18N
        jPanel1.add(PalabrasLabel);
        PalabrasLabel.setBounds(630, 140, 180, 180);

        LetrasDeArribaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/15primeras_letras.png"))); // NOI18N
        jPanel1.add(LetrasDeArribaLabel);
        LetrasDeArribaLabel.setBounds(0, 0, 910, 71);

        LetrasDeAbajoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/15ultimas_letras.png"))); // NOI18N
        jPanel1.add(LetrasDeAbajoLabel);
        LetrasDeAbajoLabel.setBounds(0, 550, 910, 80);

        LetrasLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/letras_2.png"))); // NOI18N
        jPanel1.add(LetrasLabel);
        LetrasLabel.setBounds(80, 140, 180, 180);

        SilabasLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silabas.png"))); // NOI18N
        jPanel1.add(SilabasLabel);
        SilabasLabel.setBounds(360, 280, 180, 180);

        Nivel1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nivel1.png"))); // NOI18N
        jPanel1.add(Nivel1Label);
        Nivel1Label.setBounds(80, 320, 540, 60);

        Nivel2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nivel2.png"))); // NOI18N
        jPanel1.add(Nivel2Label);
        Nivel2Label.setBounds(360, 460, 180, 60);

        Nivel3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nivel3.png"))); // NOI18N
        jPanel1.add(Nivel3Label);
        Nivel3Label.setBounds(630, 320, 180, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoSilla.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 909, 626);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConfiguracionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfiguracionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfiguracionButtonActionPerformed

    private void RegresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarButtonActionPerformed
        //boton para volver al menu principal, se declara tamaño y al centro
        stopSound();
        MainMenu Menu = new MainMenu();
        Menu.setSize(909, 655);
        Menu.setLocationRelativeTo(null);
        Menu.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_RegresarButtonActionPerformed

    private void LetrasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetrasButtonActionPerformed
        //boton para ir a la interfaz letras, se declara tamaño y al centro
        stopSound();
        LetraA Letras = new LetraA();
        Letras.setSize(909, 655);
        Letras.setLocationRelativeTo(null);
        Letras.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LetrasButtonActionPerformed

    private void SilabasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SilabasButtonActionPerformed
        //boton para ir a la interfaz silabas, se declara tamaño y al centro
        stopSound();
        SilabaTaza Silabas = new SilabaTaza();
        Silabas.setSize(909, 655);
        Silabas.setLocationRelativeTo(null);
        Silabas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SilabasButtonActionPerformed

    private void PalabrasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PalabrasButtonActionPerformed
        //boton para ir a la interfaz palabras
        stopSound();
        TrasladadorPalabras Siguiente = new TrasladadorPalabras();
        Siguiente.ComparaPalabras();
        this.dispose();
    }//GEN-LAST:event_PalabrasButtonActionPerformed

    private void AlfabetoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlfabetoButtonActionPerformed
        //boton para ir a la interfaz de repaso de letras, se declara tamaño y al centro
        stopSound();
        RepasarMenu Repasar = new RepasarMenu();
        Repasar.setSize(909, 655);
        Repasar.setLocationRelativeTo(null);
        Repasar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AlfabetoButtonActionPerformed

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        //detiene el audio que se este reproduciendo y luego reproduce uno especifico
        stopSound(); 
        playSound("Elige_un_nivel");
    }//GEN-LAST:event_PlayButtonActionPerformed

     public void botonesTransparentes(){
        LetrasButton.setOpaque(false);
        LetrasButton.setContentAreaFilled(false);
        LetrasButton.setBorderPainted(false);
        LetrasButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        LetrasButton.setFocusPainted(false);
        SilabasButton.setOpaque(false);
        SilabasButton.setContentAreaFilled(false);
        SilabasButton.setBorderPainted(false);
        SilabasButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        SilabasButton.setFocusPainted(false);
        PalabrasButton.setOpaque(false);
        PalabrasButton.setContentAreaFilled(false);
        PalabrasButton.setBorderPainted(false);
        PalabrasButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        PalabrasButton.setFocusPainted(false);
        ConfiguracionButton.setOpaque(false);
        ConfiguracionButton.setContentAreaFilled(false);
        ConfiguracionButton.setBorderPainted(false);
        ConfiguracionButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ConfiguracionButton.setFocusPainted(false);
        AlfabetoButton.setOpaque(false);
        AlfabetoButton.setContentAreaFilled(false);
        AlfabetoButton.setBorderPainted(false);
        AlfabetoButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        AlfabetoButton.setFocusPainted(false);
        RegresarButton.setOpaque(false);
        RegresarButton.setContentAreaFilled(false);
        RegresarButton.setBorderPainted(false);
        RegresarButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        RegresarButton.setFocusPainted(false);
        PlayButton.setOpaque(false);
        PlayButton.setContentAreaFilled(false);
        PlayButton.setBorderPainted(false);
        PlayButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        PlayButton.setFocusPainted(false);
 }
     
         private void playSound(String File) { // Play a wav file specified by fileName
        try {
             String path = "src/sonidos/" + File + ".wav";
             File file = new File(path);
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(file);
            clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (Exception e) {
        }
    }
    //metodo para detener el sonido
    private void stopSound() { // Play a wav file specified by fileName
        try {
            clip.stop();
        } catch (Exception e) {
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FabricaDePalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FabricaDePalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FabricaDePalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FabricaDePalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FabricaDePalabras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlfabetoButton;
    private javax.swing.JButton ConfiguracionButton;
    private javax.swing.JButton LetrasButton;
    private javax.swing.JLabel LetrasDeAbajoLabel;
    private javax.swing.JLabel LetrasDeArribaLabel;
    private javax.swing.JLabel LetrasLabel;
    private javax.swing.JLabel Nivel1Label;
    private javax.swing.JLabel Nivel2Label;
    private javax.swing.JLabel Nivel3Label;
    private javax.swing.JButton PalabrasButton;
    private javax.swing.JLabel PalabrasLabel;
    private javax.swing.JButton PlayButton;
    private javax.swing.JButton RegresarButton;
    private javax.swing.JButton SilabasButton;
    private javax.swing.JLabel SilabasLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
