/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import canciones.MenuCanciones;
import complementos.TrasladadorTeclado;
import java.awt.Cursor;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JFrame;
import palabras.PalabraCohete;

/**
 *
 * @author Alberto Villarreal
 */
public class MainMenu extends javax.swing.JFrame {
        //Recalcar el tamaño de la interfaz
	private final int WINDOW_WIDTH = 909;
	private final int WINDOW_HEIGHT = 655;
        public Clip clip;
        Configuracion Conf = new Configuracion();
		
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        // Call JFrame constructor.
                botonesTransparentes(); //manda a llamar al metodo botonesTransparentes
               // this.setLocationRelativeTo(null); //Para que apareza la interfaz en el centro
		// Set window size.
		//setSize(WINDOW_WIDTH, WINDOW_HEIGHT);
                setTitle("LEON"); //Titulo del programa
                setResizable(false); //Remueve el boton de maximizar pantalla
		
		// Specify what happens when close button is clicked.
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		// Generate an instance of the class that accesses
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FabPalButton = new javax.swing.JButton();
        MemoramaButton = new javax.swing.JButton();
        TecladoButton = new javax.swing.JButton();
        ZonaAudButton = new javax.swing.JButton();
        ConfiguracionButton = new javax.swing.JButton();
        LetrasDeArribaLabel = new javax.swing.JLabel();
        LetrasDeAbajoLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        GusanoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        FabPalButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/kindergarten.png"))); // NOI18N
        FabPalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FabPalButtonActionPerformed(evt);
            }
        });
        jPanel1.add(FabPalButton);
        FabPalButton.setBounds(100, 230, 140, 160);

        MemoramaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/memory-card.png"))); // NOI18N
        MemoramaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemoramaButtonActionPerformed(evt);
            }
        });
        jPanel1.add(MemoramaButton);
        MemoramaButton.setBounds(230, 330, 150, 170);

        TecladoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/typing.png"))); // NOI18N
        TecladoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TecladoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(TecladoButton);
        TecladoButton.setBounds(490, 330, 160, 170);

        ZonaAudButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/audiobook.png"))); // NOI18N
        ZonaAudButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZonaAudButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ZonaAudButton);
        ZonaAudButton.setBounds(360, 230, 150, 160);

        ConfiguracionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuracion_6.png"))); // NOI18N
        ConfiguracionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfiguracionButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ConfiguracionButton);
        ConfiguracionButton.setBounds(0, 490, 60, 70);

        LetrasDeArribaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/15primeras_letras.png"))); // NOI18N
        jPanel1.add(LetrasDeArribaLabel);
        LetrasDeArribaLabel.setBounds(0, 0, 910, 71);

        LetrasDeAbajoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/15ultimas_letras.png"))); // NOI18N
        jPanel1.add(LetrasDeAbajoLabel);
        LetrasDeAbajoLabel.setBounds(0, 540, 920, 100);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("© 2018 Betusto");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(370, 520, 140, 40);

        GusanoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Gusano_prueba7.png"))); // NOI18N
        jPanel1.add(GusanoLabel);
        GusanoLabel.setBounds(90, 20, 862, 530);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoMenu.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 66, 909, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FabPalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FabPalButtonActionPerformed
        FabricaDePalabras FabPal = new FabricaDePalabras();
        FabPal.setSize(909, 655);
        FabPal.setLocationRelativeTo(null);	
        FabPal.setVisible(true);
        Conf.dispose();
        this.dispose();//Destruye la interfaz para liberar memoria
    }//GEN-LAST:event_FabPalButtonActionPerformed

    private void MemoramaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemoramaButtonActionPerformed
        //playSound("Memorama");
        JuegoDelMemorama Memorama = new JuegoDelMemorama();
        Memorama.setSize(909, 655);
        Memorama.setLocationRelativeTo(null);
        Memorama.setVisible(true);
        Conf.dispose();
        this.dispose();//Destruye la interfaz para liberar memoria
    }//GEN-LAST:event_MemoramaButtonActionPerformed

    private void TecladoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TecladoButtonActionPerformed
        //playSound("Practica_con_el_teclado");
        //playSound("Practica_con_el_teclado");
                TrasladadorTeclado Siguiente = new TrasladadorTeclado();
                Siguiente.CompararTeclado();
                Conf.dispose();
                this.dispose();
    }//GEN-LAST:event_TecladoButtonActionPerformed

    private void ZonaAudButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZonaAudButtonActionPerformed
        playSound("Zona_Auditiva");
        MenuCanciones ZonaAud = new MenuCanciones();
        ZonaAud.setSize(909, 655);
        ZonaAud.setLocationRelativeTo(null);
        ZonaAud.setVisible(true);
        Conf.dispose();
        this.dispose();//Destruye la interfaz para liberar memoria
    }//GEN-LAST:event_ZonaAudButtonActionPerformed

    private void ConfiguracionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfiguracionButtonActionPerformed
        // TODO add your handling code here:
                Conf.setSize(310, 437);
                Conf.setLocationRelativeTo(null);
                Conf.setVisible(true);
    }//GEN-LAST:event_ConfiguracionButtonActionPerformed
    public void botonesTransparentes(){
        FabPalButton.setOpaque(false);
        FabPalButton.setContentAreaFilled(false);
        FabPalButton.setBorderPainted(false);
        FabPalButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        FabPalButton.setFocusPainted(false);
        MemoramaButton.setOpaque(false);
        MemoramaButton.setContentAreaFilled(false);
        MemoramaButton.setBorderPainted(false);
        MemoramaButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        MemoramaButton.setFocusPainted(false);
        ZonaAudButton.setOpaque(false);
        ZonaAudButton.setContentAreaFilled(false);
        ZonaAudButton.setBorderPainted(false);
        ZonaAudButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ZonaAudButton.setFocusPainted(false);
        TecladoButton.setOpaque(false);
        TecladoButton.setContentAreaFilled(false);
        TecladoButton.setBorderPainted(false);
        TecladoButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        TecladoButton.setFocusPainted(false);
        ConfiguracionButton.setOpaque(false);
        ConfiguracionButton.setContentAreaFilled(false);
        ConfiguracionButton.setBorderPainted(false);
        ConfiguracionButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ConfiguracionButton.setFocusPainted(false);
    }
    
        private void playSound(String File) { // Play a wav file specified by fileName
        try {
            String path = "src/sonidos/" + File + ".wav";
            File file = new File(path);
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(file);
            clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (Exception e) {
        }
    }
    
    //metodo para detener el sonido
    private void stopSound() { // Play a wav file specified by fileName
        try {
            clip.stop();
        } catch (Exception e) {
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FabricaDePalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FabricaDePalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FabricaDePalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FabricaDePalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FabricaDePalabras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfiguracionButton;
    private javax.swing.JButton FabPalButton;
    private javax.swing.JLabel GusanoLabel;
    private javax.swing.JLabel LetrasDeAbajoLabel;
    private javax.swing.JLabel LetrasDeArribaLabel;
    private javax.swing.JButton MemoramaButton;
    private javax.swing.JButton TecladoButton;
    private javax.swing.JButton ZonaAudButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
