/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import complementos.TrasladadorPalabras;
import letras.LetraA;
import java.awt.Cursor;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JFrame;
import repasar.RepasarMenu;
import silabas.SilabaTaza;
/**
 *
 * @author Alberto Villarreal
 */
public class ZonaAuditiva extends javax.swing.JFrame {
        //Recalcar el tamaño de la interfaz
	private final int WINDOW_WIDTH = 909;
	private final int WINDOW_HEIGHT = 655;
    /**
     * Creates new form FabricaDePalabras
     */
    public ZonaAuditiva() {
        initComponents();
                //botonesTransparentes(); //manda a llamar al metodo botonesTransparentes
                botonesTransparentes();
                //this.setLocationRelativeTo(null); //Para que apareza la interfaz en el centro
		// Set window size.
		setSize(WINDOW_WIDTH, WINDOW_HEIGHT);
                setTitle("LEON"); //Titulo del programa
		setResizable(false); //Remueve el boton de maximizar pantalla
		// Specify what happens when close button is clicked.
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		// Generate an instance of the class that accesses
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ConfiguracionButton = new javax.swing.JButton();
        RegresarButton = new javax.swing.JButton();
        PlayButton = new javax.swing.JButton();
        LetrasDeArribaLabel = new javax.swing.JLabel();
        LetrasDeAbajoLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        ConfiguracionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuracion_6.png"))); // NOI18N
        ConfiguracionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfiguracionButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ConfiguracionButton);
        ConfiguracionButton.setBounds(0, 490, 60, 70);

        RegresarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar_2.png"))); // NOI18N
        RegresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RegresarButton);
        RegresarButton.setBounds(830, 490, 80, 70);

        PlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/play-bdutton2.png"))); // NOI18N
        jPanel1.add(PlayButton);
        PlayButton.setBounds(420, 80, 70, 70);

        LetrasDeArribaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/15primeras_letras.png"))); // NOI18N
        jPanel1.add(LetrasDeArribaLabel);
        LetrasDeArribaLabel.setBounds(0, 0, 910, 71);

        LetrasDeAbajoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/15ultimas_letras.png"))); // NOI18N
        jPanel1.add(LetrasDeAbajoLabel);
        LetrasDeAbajoLabel.setBounds(0, 550, 910, 80);
        jPanel1.add(jButton1);
        jButton1.setBounds(510, 180, 230, 270);
        jPanel1.add(jButton2);
        jButton2.setBounds(170, 180, 230, 270);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarButtonActionPerformed
        //boton para volver al menu principal, se declara tamaño y al centro
        MainMenu Menu = new MainMenu();
        Menu.setSize(909, 655);
        Menu.setLocationRelativeTo(null);
        Menu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_RegresarButtonActionPerformed

    private void ConfiguracionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfiguracionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfiguracionButtonActionPerformed

     public void botonesTransparentes(){
        ConfiguracionButton.setOpaque(false);
        ConfiguracionButton.setContentAreaFilled(false);
        ConfiguracionButton.setBorderPainted(false);
        ConfiguracionButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ConfiguracionButton.setFocusPainted(false);
        RegresarButton.setOpaque(false);
        RegresarButton.setContentAreaFilled(false);
        RegresarButton.setBorderPainted(false);
        RegresarButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        RegresarButton.setFocusPainted(false);
        PlayButton.setOpaque(false);
        PlayButton.setContentAreaFilled(false);
        PlayButton.setBorderPainted(false);
        PlayButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        PlayButton.setFocusPainted(false);
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZonaAuditiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZonaAuditiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZonaAuditiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZonaAuditiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZonaAuditiva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfiguracionButton;
    private javax.swing.JLabel LetrasDeAbajoLabel;
    private javax.swing.JLabel LetrasDeArribaLabel;
    private javax.swing.JButton PlayButton;
    private javax.swing.JButton RegresarButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
